baseURL = 'https://mapoli.net/'
languageCode = 'en-us'
title = 'mapoli.net'
theme = 'hugonews'
paginate = '25'
googleAnalytics = 'G-MPR725SZRG'
disqusShortname = 'mapoli'

[params]
    description = 'A choice selection of Massachusetts political news.'

[taxonomies]
    tag = 'tags'
    category = 'categories'
    site = 'sites'

[permalinks]
  items = '/:year/:month/:day/:title/'
