baseURL = 'https://mapoli.net/'
languageCode = 'en-us'
title = 'mapoli.net'
theme = 'hugonews'
paginate = '25'
GoogleAnalytics = 'G-SQXW0YVJSJ'

[taxonomies]
    tag = 'tags'
    category = 'categories'
    site = 'sites'

[permalinks]
  items = '/:year/:month/:title/'
